import LocalizedStrings from "react-native-localization";

export const variableStrings = new LocalizedStrings({
  "en-US": {
    // Common strings
    save: "Save",
    signIn: "Sign In",
    email: "Email",
    selectFile: "Select File",
    maxUploadSize: "Attachment (Max Upload size 5MB)",
    phoneNumber: "Phone Number",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    currentPass: "Current Password",
    newPassword: "New Password",
    forgotPassword: "Forgot Password ?",
    or: "Or",
    signUpMessage: "Don't have an account?",
    continueWithEmail: "Continue With Email",
    signUp: "Sign Up",
    next: "Next",
    verify: "Verify",
    selectGender: "Select Gender",
    plus18: "Are you over 18 ?",
    loginSuccessMessage: "Login Successful",
    not18Plus: "You are not eligible for this app because you are not over 18.",
    confirmPassword: "Confirm Password",
    sigInMessage: "Already have an account !",
    userName: "User Name",
    username: "Username",
    firstName: "First Name",
    lastName: "Last Name",
    gender: "Gender",
    mobileNumber: "Mobile Number",
    location: "Location",
    select: "Select",
    message: "Message",
    submit: "Submit",
    yes: "Yes",
    no: "No",
    noDataFound: "No Data Found!",
    noInternetConnection: "No Internet Connection!",
    tryAgain: 'Try Again!',
    verified: "Verified",
    resend: "Resend",
    verificationCode: "Verification Code",
    verificationCodeMessage: "Please type the verification code sent to ",
    congratulations: "Congratulations!!",
    shareWithFriends: "Share with Friends",
    settings: "Settings",
    otpMessage: "Please fill your otp.",
    validOtp: "Please fill valid otp.",
    gettingSomeError: "Getting some error, please try again later.",
    selectImageMessage: "Please select an image first !",
    home: "Home",
    aboutUs: "About Us",
    myAccount: "My Account",
    FAQs: "FAQs",
    track: "Track",
    country: "Country",
    chat: "Chat",
    policies: "Policies",
    notification: "Notification",
    privacy: "Privacy",
    aboutUS: "About Us",
    contactUs: "Contact Us",
    tc: "Term & Condition",
    appVersion: "App Version",
    changePassword: "Change Password",
    updatePassword: "Update Password",
    deleteAccount: "Delete Account",
    clearAll: "Clear All",
    searchHere: "Search here ...",
    open: "open",
    to: "to",
    register: "Register",
    products: "Products",
    fillMandatoryInfo: "Fill mandatory info.",
    updateProfile: "Update Profile",
    joinNow: "Join Now",
    id: "Id : ",
    paymentProcess: "Payment Process",
    paypal: "Paypal",
    stripe: "Stripe",
    cash: "Cash",
    selectAccountType: "Select Account Type",
    seller: "Seller",
    buyer: "Buyer",
    continue: "Continue",
    total: "Total",
    confirmOrder: "Confirm Order",
    dollar: "$",
    dash: " - ",
    rupee: "₹",
    male: "Male",
    female: "Female",
    enterEmail: "Enter your email",
    enterFirstName: "Enter First Name",
    enterLocation: "Enter your address",
    enterLastName: "Enter Last Name",
    enterPassword: "Enter your password",
    enterMobileNumber: "Enter Mobile Number",
    forgotPsw: "Forgot Password?",
    resetPassword: "Reset Password",
    rememberMe: "Remember Me",
    login: "Log into your account",
    signOut: "Sign Out",
    logout: "Logout",
    edit: "Edit",
    loginToContinue: "Login to continue",
    createAccount: "Create an account",
    termPrivacy: "T&C / Privacy policy",
    checkNetInfoMessage: "Please check your internet connection and try again!",

    // Camera Modal
    selectPhoto: "Select Photo",
    chooseImage: "Choose Image From Gallery",
    captureImage: "Capture Image From Camera",
    cancel: "Cancel",
    fileTypeMessage:
      "Sorry! Please upload image, this file type isn't a valid image. Only JPG, JPEG and PNG files are allowed",

    // Social Login messages

    fbLoginCancelled: "Facebook login cancelled.",
    fbLoginFail: "Login fail with error:",
    fbLoginSuccess: "Facebook login succeeded.",
    fbGettingError: "Error getting data from facebook.",
    googleLoginSuccess: "Google login succeeded.",
    googleLoginCancelled: "Google login cancelled.",
    googleLoginAlreadyInProcess: "Google login already in process.",
    googlePlayServicesNotAvailableOrOutdated:
      "Google play services not available or outdated.",
    googleUserNotLoggedIn: "Google user not logged in.",
    googleGettingSomeError:
      "Google getting some error while getting user information.",

    errors: {
      noSpace: "No Space Allowed",
      requiredField: "This field is required.",
      specialCharacterNotAllowed: "special character not allowed",
      validEmailError: "Enter a valid email.",
      validEmailMobileError: "Enter a valid email or mobile number.",
      validEmailMobileError: "Enter a valid email.",
      onlyAlphabetsAllowed: "Only contain alphabetical characters.",
      Max_LimitLogin: "Please enter minimum eight/8 characters",
      Max_Limit:
        "Password Must be [8 to 20 characters which contain at least one lowercase letter, one uppercase letter, one numeric digit, and one special character]",
      MatchPass: "New Password and Repeat Password does not match",
      enterValidMobileNo: "Enter a valid mobile Number",
    },
  },
});

export const constants = {
  USER_DETAILS: "",
  URL: "",
  BASE_URL: "",
  SIGN_UP: "signup",
};
